services:
  - type: web
    name: boss
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    plan: free
    envVars:
      - key: BOT_TOKEN
        value: your-telegram-bot-token
      - key: MONGO_URI
        value: your-mongodb-uri
      - key: SHORTNER_API
        value: your-shortner-api-key
      - key: FLASK_URL
        value: https://telegram-like-bot.onrender.com
      - key: HOW_TO_VERIFY_URL
        value: https://your-help-link.com